# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build app and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.source=https://github.com/conductor-oss/conductor

      - uses: tdemin/find-latest-tag@v1
        id: latest-tag
        with:
          repo: https://github.com/conductor-oss/conductor
          tag: '^v3'

      - name: Get tag
        id: get-tag
        run: |
          VERSION=$(echo "${{ steps.latest-tag.outputs.tag }}")
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: conductor-oss/conductor
          ref: ${{ steps.latest-tag.outputs.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          file: docker/server/Dockerfile
          push: true
          tags: ghcr.io/bacon-factory/${{ github.event.repository.name }}:latest,ghcr.io/bacon-factory/${{ github.event.repository.name }}:${{ steps.latest-tag.outputs.tag }},ghcr.io/bacon-factory/${{ github.event.repository.name }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}